/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Mirror.gltf --transform
Author: YouniqueĪdeaStudio (https://sketchfab.com/sinnervoncrawsz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mirror-ikea-trensum-258799ba04874be4a972b13eaf180fa0
Title: MIRROR - IKEA TRENSUM
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Mirror-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.81}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.BASE_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.FOOT_Material005_0.geometry} material={materials['Material.002']} position={[0, 7.28, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.C_Material003_0.geometry} material={materials['Material.002']} position={[0, 22.93, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.CLAMP_Material004_0.geometry} material={materials['Material.004']} position={[0, 22.92, 0]} rotation={[-1.83, 0, 0]} scale={100} />
          <mesh geometry={nodes.FRAME_Material006_0.geometry} material={materials['Material.002']} position={[0, 22.92, 0]} rotation={[-1.83, 0, 0]} scale={100} />
          <mesh geometry={nodes.MIRROR_2_Material009_0.geometry} material={materials['Material.009']} position={[0, 22.92, -0.01]} rotation={[-1.83, 0, 0]} scale={100} />
          <mesh geometry={nodes.BOLT_Material008_0.geometry} material={materials['Material.008']} position={[0, 22.93, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.ring_Material010_0.geometry} material={materials['Material.002']} position={[0, 0.63, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.MIRROR_2001_Material009_0.geometry} material={materials['Material.009']} position={[0, 22.93, 0.01]} rotation={[1.31, 0, 0]} scale={100} />
          <mesh geometry={nodes['IMG-1872_IMG-1872_0'].geometry} material={materials['IMG-1872']} position={[0, 0.16, -3.85]} rotation={[Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Mirror-transformed.glb')
